#!/bin/sh

DOWNLOADING_DIR="${HOME}/downloading"

inotifywait -mr -e close_write --format '%w%f' "${DOWNLOADING_DIR}" | while read -r FILE_PATH; do
  FILE_DIR_PATH="$(dirname "${FILE_PATH}")"
  FILE_NAME="$(basename "${FILE_PATH}")"
  if [ "${FILE_NAME}" = 'galleryinfo.txt' ]; then
    archive-gallery "${FILE_DIR_PATH}"
  fi
done
